# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  my-title:
    description: 'How should we address you?'
    required: false
    default: ''
outputs:
  greeting:
    description: 'The greeting message'
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-w'
    - "${{ inputs.who-to-greet }}"
    - '-t'
    - "${{ inputs.my-title }}"
    - '-d'
